title: Mail Pathway
description: Mail redirect
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mail.adriandiaz.ca" 
gems:
  - jekyll-sitemap
  - jekyll-redirect-from

# Build settings
markdown: kramdown
theme: minima

include: ["_pages"]
